### ISSUE TITLE
Issue with sudo docker build -t taxidemo_preprocess_data preprocess_data

### ISSUE THREAD

**Issue by BelliTechViking** [claudiofahey/taxidemo#1]
I get the errors below. It then starts doing something else showing everything in red text in the console. That output went on for over an hour. At the end, it shows "The command '/bin/sh -c conda install -y jupyter' returned a non-zero code: 1"

Status: Downloaded newer image for continuumio/anaconda3:latest
 ---> 32046080a4e9
Step 2/16 : RUN conda install -y jupyter
 ---> Running in ba14cb5cd647
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...

**Comment by BelliTechViking** [comment]
I had to modify the Dockerfile to use a specific version of Anaconda.

**Comment by claudiofahey** [comment]
Thanks for letting me know. It would be appreciated if you could send a pull request with this fix.
